### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by tjvc** [mark-dce/lse-camp#11]
Include a welcome to Hydra Camp and information about the repo

**Comment by mark-dce** [comment]
How about adding a hydra camp logo? Hint, look in your samples directory in the tutorial.

**Comment by mark-dce** [comment]
Assign to Bhavana & Thom

**Comment by mark-dce** [comment]
We might also want to give some setup instructions

* Clone this repo using `git clone https://github.com/mark-dce/lse-camp.git`
* Change to the project directory `cd lse-camp`
* Run any pending migrations `rake db:migrate`
* Start jetty `rake jetty:start`
* Run the application `rails s`
