### ISSUE TITLE
Add an alternative title to the metadata model for a Book

### ISSUE THREAD

**Issue by mark-dce** [mark-dce/lse-camp#2]

**Comment by mark-dce** [comment]
Assign to Julie & Paul

**Comment by geekscruff** [comment]
Fixed in https://github.com/mark-dce/lse-camp/commit/42bced6607ceebc0f42caf19671ead3854936b74 

Added DC.alternative to the model
Added field to search in catalog_controller
Added field to index and show in catalog_controller
